let
    Source = Excel.Workbook(File.Contents(FilePath & "\zLookup-DQS-EEIC.xlsx"), null, true),
    EEIC_Sheet = Source{[Item="EEIC",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(EEIC_Sheet, [PromoteAllScalars=true]),
    #"Filtered Status to Current" = Table.SelectRows(#"Promoted Headers", each ([STATUS] = "Current")),
    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Status to Current",{"EEIC", "TITLE", "DESCRIPTION", "OBJECT CLASS", "OBJ SUB CLASS", "DODEE"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"TITLE", "Commodity-Title"}, {"DESCRIPTION", "Commodity-Description"}, {"OBJECT CLASS", "Obj Class"}, {"OBJ SUB CLASS", "Obj SubClass"}, {"DODEE", "DoDEE"}}),
    #"Added Commodity-Group Column" = Table.AddColumn(#"Renamed Columns", "Commodity-Grouping", each if Text.StartsWith([EEIC], "11") then "CivPay" else if Text.StartsWith([EEIC], "12") then "CivPay" else if Text.StartsWith([EEIC], "13") then "CivPay" else if Text.StartsWith([EEIC], "15") then "CivPay" else if Text.StartsWith([EEIC], "17") then "CivPay" else if Text.StartsWith([EEIC], "721") then "CivPay" else if Text.StartsWith([EEIC], "3") then "CivPay" else if Text.StartsWith([EEIC], "47") then "Leased Space & Rental" else if Text.StartsWith([EEIC], "558") then "Education" else if Text.StartsWith([EEIC], "50100") then "Printing" else if Text.StartsWith([EEIC], "502") then "Printing" else if Text.StartsWith([EEIC], "503") then "Printing" else if Text.StartsWith([EEIC], "54900") then "Services Furnished by Others" else if Text.StartsWith([EEIC], "75000") then "Services Furnished by Others" else if Text.StartsWith([EEIC], "756") then "Services Furnished by Others" else if Text.StartsWith([EEIC], "581") then "Associate TTF Prog" else if Text.StartsWith([EEIC], "638") then "Support Equip" else if Text.StartsWith([EEIC], "804") then "Support Equip" else if Text.StartsWith([EEIC], "578") then "CLS & Sustaining Eng" else if Text.StartsWith([EEIC], "579") then "CLS & Sustaining Eng" else if Text.StartsWith([EEIC], "583") then "CLS & Sustaining Eng" else if Text.StartsWith([EEIC], "590") then "CLS & Sustaining Eng" else if Text.StartsWith([EEIC], "6191F") then "CID Furniture" else if Text.StartsWith([EEIC], "6390B") then "CID Furniture" else if Text.StartsWith([EEIC], "672") then "Claims & Indemnities" else if Text.StartsWith([EEIC], "69200") then "Claims & Indemnities" else if Text.StartsWith([EEIC], "480") then "Utilities" else if Text.StartsWith([EEIC], "61211") then "Utilities" else if Text.StartsWith([EEIC], "642") then "Utilities" else if Text.StartsWith([EEIC], "44") then "Communications" else if Text.StartsWith([EEIC], "701") then "Communications" else if Text.StartsWith([EEIC], "702") then "Communications" else if Text.StartsWith([EEIC], "50504") then "IDT Lodging" else if Text.StartsWith([EEIC], "52") then "Facility Proj, Demo, A&E" else if Text.StartsWith([EEIC], "532") then "Facility Proj, Demo, A&E" else if Text.StartsWith([EEIC], "536") then "Facility Proj, Demo, A&E" else if Text.StartsWith([EEIC], "45") then "Trans and Special Travel" else if Text.StartsWith([EEIC], "46") then "Trans and Special Travel" else if Text.StartsWith([EEIC], "409CT") then "Trans and Special Travel" else if Text.StartsWith([EEIC], "43501") then "Trans and Special Travel" else if Text.StartsWith([EEIC], "43502") then "Trans and Special Travel" else if Text.StartsWith([EEIC], "43503") then "Trans and Special Travel" else if Text.StartsWith([EEIC], "43504") then "Trans and Special Travel" else if Text.StartsWith([EEIC], "409") then "Travel & PCS Travel*" else if Text.StartsWith([EEIC], "421") then "Travel & PCS Travel*" else if Text.StartsWith([EEIC], "435") then "Travel & PCS Travel*" else if Text.StartsWith([EEIC], "439") then "IP & Contract Tech Services*" else if Text.StartsWith([EEIC], "754") then "IP & Contract Tech Services*" else if Text.StartsWith([EEIC], "605") then "Flying Hours*" else if Text.StartsWith([EEIC], "60902") then "Flying Hours*" else if Text.StartsWith([EEIC], "61902") then "Flying Hours*" else if Text.StartsWith([EEIC], "61952") then "Flying Hours*" else if Text.StartsWith([EEIC], "644") then "Flying Hours*" else if Text.StartsWith([EEIC], "693") then "Flying Hours*" else if [EEIC] = "69910" then "Contract Maint of Equip*" else if Text.StartsWith([EEIC], "699") then "Flying Hours*" else if [EEIC] = "63772" then "DPEM*" else if Text.StartsWith([EEIC], "627") then "ADPE*" else if Text.StartsWith([EEIC], "637") then "ADPE*" else if Text.StartsWith([EEIC], "532") then "Unknown" else if Text.StartsWith([EEIC], "536") then "Unknown" else if Text.StartsWith([EEIC], "53") then "Other CE Services" else if Text.StartsWith([EEIC], "651") then "Other CE Services" else if Text.StartsWith([EEIC], "683") then "Other CE Services" else if Text.StartsWith([EEIC], "684") then "Other CE Services" else if [EEIC] = "54900" then "Unknown" else if Text.StartsWith([EEIC], "54") then "DPEM*" else if Text.StartsWith([EEIC], "560") then "DPEM*" else if Text.StartsWith([EEIC], "642") then "Unknown" else if Text.StartsWith([EEIC], "644") then "Unknown" else if Text.StartsWith([EEIC], "64") then "Supplies/Equip*" else if Text.StartsWith([EEIC], "56") then "Contract Maint of Equip*" else if Text.StartsWith([EEIC], "605") then "Unknown" else if Text.StartsWith([EEIC], "60") then "Supplies/Equip*" else if Text.StartsWith([EEIC], "61") then "Supplies/Equip*" else if Text.StartsWith([EEIC], "62") then "Supplies/Equip*" else if Text.StartsWith([EEIC], "63") then "Supplies/Equip*" else if Text.StartsWith([EEIC], "570") then "Contract Operated Inst (A76)" else if Text.StartsWith([EEIC], "595") then "Contract Operated Inst (A76)" else if [EEIC] = "50504" then "Unknown" else if [EEIC] = "59900" then "Unknown" else if Text.StartsWith([EEIC], "590") then "Unknown" else if Text.StartsWith([EEIC], "598") then "Unknown" else if [EEIC] = "51400" then "Misc Contract Services*" else if Text.StartsWith([EEIC], "504") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "505") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "506") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "554") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "555") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "556") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "557") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "559") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "571") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "572") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "573") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "574") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "575") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "59") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "759") then "Misc Contract Services*" else if Text.StartsWith([EEIC], "805") then "Misc Contract Services*" else "Unknown"),
    #"Added Commodity-Program Type" = Table.AddColumn(#"Added Commodity-Group Column", "Commodity-Program Type", each if Text.StartsWith([EEIC], "11") then "Command" else if Text.StartsWith([EEIC], "12") then "Command" else if Text.StartsWith([EEIC], "13") then "Command" else if Text.StartsWith([EEIC], "15") then "Command" else if Text.StartsWith([EEIC], "17") then "Command" else if Text.StartsWith([EEIC], "721") then "Command" else if Text.StartsWith([EEIC], "3") then "Command" else if Text.StartsWith([EEIC], "47") then "Unit" else if Text.StartsWith([EEIC], "558") then "Unit" else if Text.StartsWith([EEIC], "50100") then "Unit" else if Text.StartsWith([EEIC], "502") then "Unit" else if Text.StartsWith([EEIC], "503") then "Unit" else if Text.StartsWith([EEIC], "54900") then "Unit" else if Text.StartsWith([EEIC], "75000") then "Unit" else if Text.StartsWith([EEIC], "756") then "Unit" else if Text.StartsWith([EEIC], "581") then "Command" else if Text.StartsWith([EEIC], "638") then "Command" else if Text.StartsWith([EEIC], "804") then "Command" else if Text.StartsWith([EEIC], "578") then "Command" else if Text.StartsWith([EEIC], "579") then "Command" else if Text.StartsWith([EEIC], "583") then "Command" else if Text.StartsWith([EEIC], "590") then "Command" else if Text.StartsWith([EEIC], "6191F") then "Command" else if Text.StartsWith([EEIC], "6390B") then "Command" else if Text.StartsWith([EEIC], "672") then "Unit" else if Text.StartsWith([EEIC], "69200") then "Unit" else if Text.StartsWith([EEIC], "480") then "Command" else if Text.StartsWith([EEIC], "61211") then "Command" else if Text.StartsWith([EEIC], "642") then "Command" else if Text.StartsWith([EEIC], "44") then "Unit" else if Text.StartsWith([EEIC], "701") then "Unit" else if Text.StartsWith([EEIC], "702") then "Unit" else if Text.StartsWith([EEIC], "50504") then "Unit" else if Text.StartsWith([EEIC], "52") then "Command" else if Text.StartsWith([EEIC], "532") then "Command" else if Text.StartsWith([EEIC], "536") then "Command" else if Text.StartsWith([EEIC], "45") then "Unit" else if Text.StartsWith([EEIC], "46") then "Unit" else if Text.StartsWith([EEIC], "409CT") then "Unit" else if Text.StartsWith([EEIC], "43501") then "Unit" else if Text.StartsWith([EEIC], "43502") then "Unit" else if Text.StartsWith([EEIC], "43503") then "Unit" else if Text.StartsWith([EEIC], "43504") then "Unit" else if Text.StartsWith([EEIC], "409") then "Unit" else if Text.StartsWith([EEIC], "421") then "Unit" else if Text.StartsWith([EEIC], "435") then "Unit" else if Text.StartsWith([EEIC], "439") then "Unit" else if Text.StartsWith([EEIC], "754") then "Unit" else if Text.StartsWith([EEIC], "605") then "Command" else if Text.StartsWith([EEIC], "60902") then "Command" else if Text.StartsWith([EEIC], "61902") then "Command" else if Text.StartsWith([EEIC], "61952") then "Command" else if Text.StartsWith([EEIC], "644") then "Command" else if Text.StartsWith([EEIC], "693") then "Command" else if [EEIC] = "69910" then "Unit" else if Text.StartsWith([EEIC], "699") then "Command" else if Text.StartsWith([EEIC], "627") then "Unit" else if Text.StartsWith([EEIC], "637") then "Unit" else if Text.StartsWith([EEIC], "532") then "Unit" else if Text.StartsWith([EEIC], "536") then "Unit" else if Text.StartsWith([EEIC], "53") then "Command" else if Text.StartsWith([EEIC], "651") then "Command" else if Text.StartsWith([EEIC], "683") then "Command" else if Text.StartsWith([EEIC], "684") then "Command" else if [EEIC] = "54900" then "Unit" else if Text.StartsWith([EEIC], "54") then "Command" else if Text.StartsWith([EEIC], "560") then "Command" else if Text.StartsWith([EEIC], "642") then "Unit" else if Text.StartsWith([EEIC], "644") then "Unit" else if Text.StartsWith([EEIC], "64") then "Unit" else if Text.StartsWith([EEIC], "56") then "Unit" else if Text.StartsWith([EEIC], "605") then "Unit" else if Text.StartsWith([EEIC], "60") then "Unit" else if Text.StartsWith([EEIC], "61") then "Unit" else if Text.StartsWith([EEIC], "62") then "Unit" else if Text.StartsWith([EEIC], "63") then "Unit" else if Text.StartsWith([EEIC], "570") then "Command" else if Text.StartsWith([EEIC], "595") then "Command" else if [EEIC] = "50504" then "Unit" else if [EEIC] = "59900" then "Unit" else if Text.StartsWith([EEIC], "590") then "Unit" else if Text.StartsWith([EEIC], "598") then "Unit" else if [EEIC] = "51400" then "Unit" else if Text.StartsWith([EEIC], "504") then "Unit" else if Text.StartsWith([EEIC], "505") then "Unit" else if Text.StartsWith([EEIC], "506") then "Unit" else if Text.StartsWith([EEIC], "554") then "Unit" else if Text.StartsWith([EEIC], "555") then "Unit" else if Text.StartsWith([EEIC], "556") then "Unit" else if Text.StartsWith([EEIC], "557") then "Unit" else if Text.StartsWith([EEIC], "559") then "Unit" else if Text.StartsWith([EEIC], "571") then "Unit" else if Text.StartsWith([EEIC], "572") then "Unit" else if Text.StartsWith([EEIC], "573") then "Unit" else if Text.StartsWith([EEIC], "574") then "Unit" else if Text.StartsWith([EEIC], "575") then "Unit" else if Text.StartsWith([EEIC], "59") then "Unit" else if Text.StartsWith([EEIC], "759") then "Unit" else if Text.StartsWith([EEIC], "805") then "Unit" else "Unit"),
    #"Changed Type" = Table.TransformColumnTypes(#"Added Commodity-Program Type",{{"EEIC", type text}, {"Commodity-Title", type text}, {"Commodity-Description", type text}, {"Obj Class", type text}, {"Obj SubClass", type text}, {"DoDEE", type text}, {"Commodity-Grouping", type text}, {"Commodity-Program Type", type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","Non-DWCF Sup - ","",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Non-DWCF ","",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","DWCF ","",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Medical","Med",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Purchased ","",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4"," - ","-",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Mission","Msn",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Support","Spt",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","GSD ","",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","Transportation of People-GSA Pass Vehicle Rental","GSA Vehix Lease",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","Fuel-","",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value11" = Table.ReplaceValue(#"Replaced Value10","Purchases","",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value12" = Table.ReplaceValue(#"Replaced Value11","Environmental Permits and Fees-","Environ Permits & Fees-",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value13" = Table.ReplaceValue(#"Replaced Value12","GSD, ","",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value14" = Table.ReplaceValue(#"Replaced Value13","and","&",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value15" = Table.ReplaceValue(#"Replaced Value14","  "," ",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value16" = Table.ReplaceValue(#"Replaced Value15","PCS HHG Shipments-","PCS HHG-",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value17" = Table.ReplaceValue(#"Replaced Value16","Equipment","Equip",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value18" = Table.ReplaceValue(#"Replaced Value17","Payments","Pmts",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value19" = Table.ReplaceValue(#"Replaced Value18","Defense","Def",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value20" = Table.ReplaceValue(#"Replaced Value19","Department","Dept",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value21" = Table.ReplaceValue(#"Replaced Value20","Maintenance","Mxs",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value22" = Table.ReplaceValue(#"Replaced Value21","(Non-DWCF)","",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value23" = Table.ReplaceValue(#"Replaced Value22","(DISA)","",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value24" = Table.ReplaceValue(#"Replaced Value23","Transportation","Trans",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value25" = Table.ReplaceValue(#"Replaced Value24","Property","Prop",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value26" = Table.ReplaceValue(#"Replaced Value25","Services","Svcs",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value27" = Table.ReplaceValue(#"Replaced Value26","Travel","Trvl",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value28" = Table.ReplaceValue(#"Replaced Value27","International","Intl",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value29" = Table.ReplaceValue(#"Replaced Value28","Government","Govt",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value30" = Table.ReplaceValue(#"Replaced Value29","Expenses","Exp",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value31" = Table.ReplaceValue(#"Replaced Value30","Susistence & Person Spt-Contract Quarters: Financing Contract Quarters","IDT Lodging",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value32" = Table.ReplaceValue(#"Replaced Value31","Susistence & Person Spt-","",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value33" = Table.ReplaceValue(#"Replaced Value32","Service","Svc",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value34" = Table.ReplaceValue(#"Replaced Value33","Communications","Comm",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value35" = Table.ReplaceValue(#"Replaced Value34","Commercial","Comml",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value36" = Table.ReplaceValue(#"Replaced Value35","Other CE Svcs-","",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value37" = Table.ReplaceValue(#"Replaced Value36","Aviation Pol","AvPol",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value38" = Table.ReplaceValue(#"Replaced Value37","Restoration & Modernization","R&M",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value39" = Table.ReplaceValue(#"Replaced Value38","Environmental","Environ",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value40" = Table.ReplaceValue(#"Replaced Value39","Operations","Ops",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value41" = Table.ReplaceValue(#"Replaced Value40","Commerical","Comml",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value42" = Table.ReplaceValue(#"Replaced Value41","Conference","Conf",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value43" = Table.ReplaceValue(#"Replaced Value42","Management","Mgmt",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value44" = Table.ReplaceValue(#"Replaced Value43","Hazardous Waste","HazWaste",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value46" = Table.ReplaceValue(#"Replaced Value44","Supplies","Sply",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"}),
    #"Replaced Value47" = Table.ReplaceValue(#"Replaced Value46","Supply","Sply",Replacer.ReplaceText,{"Commodity-Title", "Commodity-Description"})
in
    #"Replaced Value47"
